services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    volumes:
      - output:/app/output
    ports:
    - "8000:80"

  layout-analysis:
    build:
      context: ./layout-analysis
      dockerfile: Dockerfile
    volumes:
      - output:/app/output
    ports:
    - "8001:80"
      
  logo-redaction:
    build:
      context: ./logo-redaction
      dockerfile: Dockerfile
    volumes:
      - output:/app/output
    ports:
      - "8002:80"

volumes:
  output: