services:
  api-gateway:
    volumes:
      - .:/workspace
      - output:/workspace/api-gateway/output
    command: /bin/sh -c "while sleep 1000; do :; done"

  layout-analysis:
    volumes:
      - .:/workspace
      - output:/workspace/layout-analysis/output
    command: /bin/sh -c "while sleep 1000; do :; done"
    
  logo-redaction:
    volumes:
      - .:/workspace
      - output:/workspace/logo-redaction/output
    command: /bin/sh -c "while sleep 1000; do :; done"