services:
  layout-analysis:
    volumes:
      - .:/workspace
    command: /bin/sh -c "while sleep 1000; do :; done"
  logo-redaction:
    volumes:
      - .:/workspace
    command: /bin/sh -c "while sleep 1000; do :; done"