services:
  layout-analysis:
    build:
      context: ./layout-analysis
      dockerfile: Dockerfile
  ports:
   - "8001:80"
      
  logo-redaction:
    build:
      context: ./logo-redaction
      dockerfile: Dockerfile