services:
  api-gateway:
    volumes:
      - .:/workspace
      - results:/workspace/api-gateway/results
    command: /bin/sh -c "while sleep 1000; do :; done"

  layout-analysis:
    volumes:
      - .:/workspace
      - results:/workspace/layout-analysis/results
    command: /bin/sh -c "while sleep 1000; do :; done"

  logo-redaction:
    volumes:
      - .:/workspace
      - results:/workspace/logo-redaction/results
    command: /bin/sh -c "while sleep 1000; do :; done"
