services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    volumes:
      - results:/app/results
    ports:
      - "80:80"

  layout-analysis:
    build:
      context: ./layout-analysis
      dockerfile: Dockerfile
    volumes:
      - results:/app/results
    ports:
      - "8001:80"

  logo-redaction:
    build:
      context: ./logo-redaction
      dockerfile: Dockerfile
    volumes:
      - results:/app/results
    ports:
      - "8002:80"

  table-extraction:
    build:
      context: ./table-extraction
      dockerfile: Dockerfile
    volumes:
      - results:/app/results
    ports:
      - "8003:80"

volumes:
  results:
